namespace PascalCompiler.Lexical.Lexer {
    using ActiproSoftware.Text;
    using ActiproSoftware.Text.Tagging.Implementation;
    using System;
    
    
    /// <summary>
    /// Represents a token tagger for the <c>Pascal</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v19.1.685.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Actipro Software LLC.
    /// Copyright (c) 2001-2020 Actipro Software LLC.  All rights reserved.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "19.1.685.0")]
    public partial class PascalTokenTagger : TokenTagger {
        
        private IPascalClassificationTypeProvider classificationTypeProviderValue;
        
        /// <summary>
        /// Initializes a new instance of the <c>PascalTokenTagger</c> class.
        /// </summary>
        /// <param name="document">The specific <see cref="ICodeDocument"/> for which this token tagger will be used.</param>
        /// <param name="classificationTypeProvider">A <see cref="IPascalClassificationTypeProvider"/> that provides classification types used by this token tagger.</param>
        public PascalTokenTagger(ICodeDocument document, IPascalClassificationTypeProvider classificationTypeProvider) : 
                base(document) {
            if ((classificationTypeProvider == null)) {
                throw new ArgumentNullException("classificationTypeProvider");
            }

            // Initialize
            this.classificationTypeProviderValue = classificationTypeProvider;
        }
        
        /// <summary>
        /// Gets the <see cref="IPascalClassificationTypeProvider"/> that provides classification types used by this token tagger.
        /// </summary>
        /// <value>The <see cref="IPascalClassificationTypeProvider"/> that provides classification types used by this token tagger.</value>
        public IPascalClassificationTypeProvider ClassificationTypeProvider {
            get {
                return this.classificationTypeProviderValue;
            }
        }
    }
}
