namespace PascalCompiler.Lexical.Lexer {
    using ActiproSoftware.Text;
    using ActiproSoftware.Text.Tagging;
    using ActiproSoftware.Text.Tagging.Implementation;
    using System;
    
    
    /// <summary>
    /// Represents a provider of <see cref="PascalTokenTagger"/> objects for documents that use the <c>PascalTokenTagger</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v19.1.685.0 (http://www.actiprosoftware.com).
    /// Generated code is based on input created by Actipro Software LLC.
    /// Copyright (c) 2001-2020 Actipro Software LLC.  All rights reserved.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "19.1.685.0")]
    public partial class PascalTokenTaggerProvider : TaggerProviderBase<PascalTokenTagger>, ICodeDocumentTaggerProvider {
        
        private IPascalClassificationTypeProvider classificationTypeProviderValue;
        
        /// <summary>
        /// Initializes a new instance of the <c>PascalTokenTaggerProvider</c> class.
        /// </summary>
        /// <param name="classificationTypeProvider">A <see cref="IPascalClassificationTypeProvider"/> that provides classification types.</param>
        public PascalTokenTaggerProvider(IPascalClassificationTypeProvider classificationTypeProvider) {
            if ((classificationTypeProvider == null)) {
                throw new ArgumentNullException("classificationTypeProvider");
            }

            // Initialize
            this.classificationTypeProviderValue = classificationTypeProvider;
        }
        
        /// <summary>
        /// Returns a tagger for the specified <see cref="ICodeDocument"/>.
        /// </summary>
        /// <typeparam name="T">The type of <see cref="ITag"/> created by the tagger.</typeparam>
        /// <param name="document">The <see cref="ICodeDocument"/> that requires a tagger.</param>
        /// <returns>A tagger for the specified <see cref="ICodeDocument"/>.</returns>
        public ITagger<T> GetTagger<T>(ICodeDocument document)
            where T : ITag {
            if (typeof(ITagger<T>).IsAssignableFrom(typeof(PascalTokenTagger))) {
                TaggerFactory factory = new TaggerFactory(this, document);
                return ((ITagger<T>)(document.Properties.GetOrCreateSingleton(typeof(ITagger<ITokenTag>), new ActiproSoftware.Text.Utility.PropertyDictionary.Creator<PascalTokenTagger>(factory.CreateTagger))));
            }
            else {
                return null;
            }
        }
        
        /// <summary>
        /// Implements a factory that can creates <see cref="PascalTokenTagger"/> objects for a document.
        /// </summary>
        public class TaggerFactory {
            
            private ICodeDocument documentValue;
            
            private PascalTokenTaggerProvider providerValue;
            
            /// <summary>
            /// Initializes a new instance of the <c>TaggerFactory</c> class.
            /// </summary>
            /// <param name="provider">The owner <see cref="PascalTokenTaggerProvider"/>.</param>
            /// <param name="document">The <see cref="ICodeDocument"/> that requires an <see cref="PascalTokenTagger"/>.</param>
            internal TaggerFactory(PascalTokenTaggerProvider provider, ICodeDocument document) {
                // Initialize
                this.providerValue = provider;
                this.documentValue = document;
            }
            
            /// <summary>
            /// Creates an <see cref="PascalTokenTagger"/> for the <see cref="ICodeDocument"/>.
            /// </summary>
            /// <returns>An <see cref="PascalTokenTagger"/> for the <see cref="ICodeDocument"/>.</returns>
            public PascalTokenTagger CreateTagger() {
                return new PascalTokenTagger(this.documentValue, this.providerValue.classificationTypeProviderValue);
            }
        }
    }
}
